// flow-typed signature: 4cb712efbfc2dc80e5c7a11969b9db7d
// flow-typed version: <<STUB>>/dictionary-en-us_v2.0.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dictionary-en-us'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dictionary-en-us' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'dictionary-en-us/index' {
  declare module.exports: $Exports<'dictionary-en-us'>;
}
declare module 'dictionary-en-us/index.js' {
  declare module.exports: $Exports<'dictionary-en-us'>;
}
