// flow-typed signature: a38935b17a8fa6e7352b7fc9604c9ba5
// flow-typed version: <<STUB>>/eslint-plugin-optimize-regex_v1.1.6/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-optimize-regex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-optimize-regex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-optimize-regex/lib/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-optimize-regex/lib/rules/optimize-regex' {
  declare module.exports: any;
}

declare module 'eslint-plugin-optimize-regex/tests/lib/rules/optimize-regex' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-optimize-regex/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-optimize-regex/lib/index'>;
}
declare module 'eslint-plugin-optimize-regex/lib/rules/optimize-regex.js' {
  declare module.exports: $Exports<'eslint-plugin-optimize-regex/lib/rules/optimize-regex'>;
}
declare module 'eslint-plugin-optimize-regex/tests/lib/rules/optimize-regex.js' {
  declare module.exports: $Exports<'eslint-plugin-optimize-regex/tests/lib/rules/optimize-regex'>;
}
