// flow-typed signature: c6041f7945a88ccfcb6eaa7896a5d6a7
// flow-typed version: <<STUB>>/eslint-plugin-array-func_v3.1.3/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-array-func'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-array-func' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-array-func/lib/helpers/call-expression' {
  declare module.exports: any;
}

declare module 'eslint-plugin-array-func/lib/type' {
  declare module.exports: any;
}

declare module 'eslint-plugin-array-func/rules/avoid-reverse' {
  declare module.exports: any;
}

declare module 'eslint-plugin-array-func/rules/from-map' {
  declare module.exports: any;
}

declare module 'eslint-plugin-array-func/rules/no-unnecessary-this-arg' {
  declare module.exports: any;
}

declare module 'eslint-plugin-array-func/rules/prefer-array-from' {
  declare module.exports: any;
}

declare module 'eslint-plugin-array-func/rules/prefer-flat-map' {
  declare module.exports: any;
}

declare module 'eslint-plugin-array-func/rules/prefer-flat' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-array-func/index' {
  declare module.exports: $Exports<'eslint-plugin-array-func'>;
}
declare module 'eslint-plugin-array-func/index.js' {
  declare module.exports: $Exports<'eslint-plugin-array-func'>;
}
declare module 'eslint-plugin-array-func/lib/helpers/call-expression.js' {
  declare module.exports: $Exports<'eslint-plugin-array-func/lib/helpers/call-expression'>;
}
declare module 'eslint-plugin-array-func/lib/type.js' {
  declare module.exports: $Exports<'eslint-plugin-array-func/lib/type'>;
}
declare module 'eslint-plugin-array-func/rules/avoid-reverse.js' {
  declare module.exports: $Exports<'eslint-plugin-array-func/rules/avoid-reverse'>;
}
declare module 'eslint-plugin-array-func/rules/from-map.js' {
  declare module.exports: $Exports<'eslint-plugin-array-func/rules/from-map'>;
}
declare module 'eslint-plugin-array-func/rules/no-unnecessary-this-arg.js' {
  declare module.exports: $Exports<'eslint-plugin-array-func/rules/no-unnecessary-this-arg'>;
}
declare module 'eslint-plugin-array-func/rules/prefer-array-from.js' {
  declare module.exports: $Exports<'eslint-plugin-array-func/rules/prefer-array-from'>;
}
declare module 'eslint-plugin-array-func/rules/prefer-flat-map.js' {
  declare module.exports: $Exports<'eslint-plugin-array-func/rules/prefer-flat-map'>;
}
declare module 'eslint-plugin-array-func/rules/prefer-flat.js' {
  declare module.exports: $Exports<'eslint-plugin-array-func/rules/prefer-flat'>;
}
