// flow-typed signature: 15883b3c62731366d113bcd33f71fde4
// flow-typed version: <<STUB>>/graphql-schema-linter_v0.2.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-schema-linter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-schema-linter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-schema-linter/lib/cli' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/configuration' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/formatters/json_formatter' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/formatters/text_formatter' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/index' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/rules/defined_types_are_used' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/rules/deprecations_have_a_reason' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/rules/enum_values_all_caps' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/rules/enum_values_have_descriptions' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/rules/enum_values_sorted_alphabetically' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/rules/fields_are_camel_cased' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/rules/fields_have_descriptions' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/rules/input_object_values_are_camel_cased' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/rules/input_object_values_have_descriptions' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/rules/relay_connection_arguments_spec' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/rules/relay_connection_types_spec' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/rules/relay_page_info_spec' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/rules/types_are_capitalized' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/rules/types_have_descriptions' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/runner' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/source_map' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/validation_error' {
  declare module.exports: any;
}

declare module 'graphql-schema-linter/lib/validator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-schema-linter/lib/cli.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/cli'>;
}
declare module 'graphql-schema-linter/lib/configuration.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/configuration'>;
}
declare module 'graphql-schema-linter/lib/formatters/json_formatter.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/formatters/json_formatter'>;
}
declare module 'graphql-schema-linter/lib/formatters/text_formatter.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/formatters/text_formatter'>;
}
declare module 'graphql-schema-linter/lib/index.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/index'>;
}
declare module 'graphql-schema-linter/lib/rules/defined_types_are_used.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/rules/defined_types_are_used'>;
}
declare module 'graphql-schema-linter/lib/rules/deprecations_have_a_reason.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/rules/deprecations_have_a_reason'>;
}
declare module 'graphql-schema-linter/lib/rules/enum_values_all_caps.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/rules/enum_values_all_caps'>;
}
declare module 'graphql-schema-linter/lib/rules/enum_values_have_descriptions.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/rules/enum_values_have_descriptions'>;
}
declare module 'graphql-schema-linter/lib/rules/enum_values_sorted_alphabetically.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/rules/enum_values_sorted_alphabetically'>;
}
declare module 'graphql-schema-linter/lib/rules/fields_are_camel_cased.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/rules/fields_are_camel_cased'>;
}
declare module 'graphql-schema-linter/lib/rules/fields_have_descriptions.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/rules/fields_have_descriptions'>;
}
declare module 'graphql-schema-linter/lib/rules/input_object_values_are_camel_cased.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/rules/input_object_values_are_camel_cased'>;
}
declare module 'graphql-schema-linter/lib/rules/input_object_values_have_descriptions.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/rules/input_object_values_have_descriptions'>;
}
declare module 'graphql-schema-linter/lib/rules/relay_connection_arguments_spec.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/rules/relay_connection_arguments_spec'>;
}
declare module 'graphql-schema-linter/lib/rules/relay_connection_types_spec.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/rules/relay_connection_types_spec'>;
}
declare module 'graphql-schema-linter/lib/rules/relay_page_info_spec.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/rules/relay_page_info_spec'>;
}
declare module 'graphql-schema-linter/lib/rules/types_are_capitalized.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/rules/types_are_capitalized'>;
}
declare module 'graphql-schema-linter/lib/rules/types_have_descriptions.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/rules/types_have_descriptions'>;
}
declare module 'graphql-schema-linter/lib/runner.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/runner'>;
}
declare module 'graphql-schema-linter/lib/source_map.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/source_map'>;
}
declare module 'graphql-schema-linter/lib/validation_error.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/validation_error'>;
}
declare module 'graphql-schema-linter/lib/validator.js' {
  declare module.exports: $Exports<'graphql-schema-linter/lib/validator'>;
}
