// flow-typed signature: 5348a7b94bd46e0a86df3aca9414e0ba
// flow-typed version: <<STUB>>/greenkeeper-lockfile_v2.8.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'greenkeeper-lockfile'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'greenkeeper-lockfile' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'greenkeeper-lockfile/ci-services/appveyor' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/ci-services/bitrise' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/ci-services/buddyworks' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/ci-services/buildkite' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/ci-services/circleci' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/ci-services/codebuild' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/ci-services/codeship' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/ci-services/drone' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/ci-services/index' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/ci-services/jenkins' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/ci-services/semaphoreci' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/ci-services/teamcity' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/ci-services/tests' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/ci-services/travis' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/ci-services/wercker' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/lib/config' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/lib/extract-dependency' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/lib/git-helpers' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/lib/ignores' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/lib/update-lockfile' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/test/lib/extract-dependencies' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/test/lib/update-lockfile' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/test/update' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/update' {
  declare module.exports: any;
}

declare module 'greenkeeper-lockfile/upload' {
  declare module.exports: any;
}

// Filename aliases
declare module 'greenkeeper-lockfile/ci-services/appveyor.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/ci-services/appveyor'>;
}
declare module 'greenkeeper-lockfile/ci-services/bitrise.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/ci-services/bitrise'>;
}
declare module 'greenkeeper-lockfile/ci-services/buddyworks.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/ci-services/buddyworks'>;
}
declare module 'greenkeeper-lockfile/ci-services/buildkite.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/ci-services/buildkite'>;
}
declare module 'greenkeeper-lockfile/ci-services/circleci.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/ci-services/circleci'>;
}
declare module 'greenkeeper-lockfile/ci-services/codebuild.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/ci-services/codebuild'>;
}
declare module 'greenkeeper-lockfile/ci-services/codeship.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/ci-services/codeship'>;
}
declare module 'greenkeeper-lockfile/ci-services/drone.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/ci-services/drone'>;
}
declare module 'greenkeeper-lockfile/ci-services/index.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/ci-services/index'>;
}
declare module 'greenkeeper-lockfile/ci-services/jenkins.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/ci-services/jenkins'>;
}
declare module 'greenkeeper-lockfile/ci-services/semaphoreci.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/ci-services/semaphoreci'>;
}
declare module 'greenkeeper-lockfile/ci-services/teamcity.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/ci-services/teamcity'>;
}
declare module 'greenkeeper-lockfile/ci-services/tests.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/ci-services/tests'>;
}
declare module 'greenkeeper-lockfile/ci-services/travis.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/ci-services/travis'>;
}
declare module 'greenkeeper-lockfile/ci-services/wercker.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/ci-services/wercker'>;
}
declare module 'greenkeeper-lockfile/lib/config.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/lib/config'>;
}
declare module 'greenkeeper-lockfile/lib/extract-dependency.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/lib/extract-dependency'>;
}
declare module 'greenkeeper-lockfile/lib/git-helpers.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/lib/git-helpers'>;
}
declare module 'greenkeeper-lockfile/lib/ignores.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/lib/ignores'>;
}
declare module 'greenkeeper-lockfile/lib/update-lockfile.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/lib/update-lockfile'>;
}
declare module 'greenkeeper-lockfile/test/lib/extract-dependencies.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/test/lib/extract-dependencies'>;
}
declare module 'greenkeeper-lockfile/test/lib/update-lockfile.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/test/lib/update-lockfile'>;
}
declare module 'greenkeeper-lockfile/test/update.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/test/update'>;
}
declare module 'greenkeeper-lockfile/update.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/update'>;
}
declare module 'greenkeeper-lockfile/upload.js' {
  declare module.exports: $Exports<'greenkeeper-lockfile/upload'>;
}
