// flow-typed signature: ce16505eeb886f616ae024c0624a1bd4
// flow-typed version: <<STUB>>/remark-lint-table-cell-padding_v1.0.3/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-lint-table-cell-padding'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-lint-table-cell-padding' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-lint-table-cell-padding/index' {
  declare module.exports: $Exports<'remark-lint-table-cell-padding'>;
}
declare module 'remark-lint-table-cell-padding/index.js' {
  declare module.exports: $Exports<'remark-lint-table-cell-padding'>;
}
