// flow-typed signature: 952e3e9997c756cff31f06f6ee634a90
// flow-typed version: <<STUB>>/remark-preset-lint-recommended_v3.0.2/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-preset-lint-recommended'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-preset-lint-recommended' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-preset-lint-recommended/index' {
  declare module.exports: $Exports<'remark-preset-lint-recommended'>;
}
declare module 'remark-preset-lint-recommended/index.js' {
  declare module.exports: $Exports<'remark-preset-lint-recommended'>;
}
