// flow-typed signature: 14c557a7aad88f190bfb589702f640fb
// flow-typed version: <<STUB>>/remark-lint-rule-style_v1.0.2/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-lint-rule-style'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-lint-rule-style' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-lint-rule-style/index' {
  declare module.exports: $Exports<'remark-lint-rule-style'>;
}
declare module 'remark-lint-rule-style/index.js' {
  declare module.exports: $Exports<'remark-lint-rule-style'>;
}
