// flow-typed signature: aa1e991175d37faff36b13d60f5013db
// flow-typed version: <<STUB>>/remark-preset-lint-consistent_v2.0.2/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-preset-lint-consistent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-preset-lint-consistent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-preset-lint-consistent/index' {
  declare module.exports: $Exports<'remark-preset-lint-consistent'>;
}
declare module 'remark-preset-lint-consistent/index.js' {
  declare module.exports: $Exports<'remark-preset-lint-consistent'>;
}
