// flow-typed signature: 4d281cf3078e8b841eed52f4e3de8b65
// flow-typed version: <<STUB>>/retext-simplify_v4.1.2/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retext-simplify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retext-simplify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'retext-simplify/index' {
  declare module.exports: $Exports<'retext-simplify'>;
}
declare module 'retext-simplify/index.js' {
  declare module.exports: $Exports<'retext-simplify'>;
}
