// flow-typed signature: fa9ec376c8ef33fc4a31fabdfec2fbff
// flow-typed version: <<STUB>>/retext-equality_v3.9.1/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retext-equality'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retext-equality' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'retext-equality/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'retext-equality/index' {
  declare module.exports: $Exports<'retext-equality'>;
}
declare module 'retext-equality/index.js' {
  declare module.exports: $Exports<'retext-equality'>;
}
declare module 'retext-equality/lib/index.js' {
  declare module.exports: $Exports<'retext-equality/lib/index'>;
}
