// flow-typed signature: e965dab3f5e7fd5a91dd93a14bc50f74
// flow-typed version: <<STUB>>/retext-redundant-acronyms_v1.2.2/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retext-redundant-acronyms'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retext-redundant-acronyms' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'retext-redundant-acronyms/index' {
  declare module.exports: $Exports<'retext-redundant-acronyms'>;
}
declare module 'retext-redundant-acronyms/index.js' {
  declare module.exports: $Exports<'retext-redundant-acronyms'>;
}
