// flow-typed signature: 1a06b899c9e2839b616f2385d01b7a59
// flow-typed version: <<STUB>>/retext-readability_v4.2.1/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retext-readability'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retext-readability' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'retext-readability/index' {
  declare module.exports: $Exports<'retext-readability'>;
}
declare module 'retext-readability/index.js' {
  declare module.exports: $Exports<'retext-readability'>;
}
