// flow-typed signature: 882bebaa97fc3fdb8861fb1eb61c9cf1
// flow-typed version: <<STUB>>/retext-assuming_v1.0.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retext-assuming'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'retext-assuming' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'retext-assuming/index' {
  declare module.exports: $Exports<'retext-assuming'>;
}
declare module 'retext-assuming/index.js' {
  declare module.exports: $Exports<'retext-assuming'>;
}
