// flow-typed signature: ae7faa3b1224e28e2ccaff642165fa7a
// flow-typed version: <<STUB>>/trash-cli_v1.4.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'trash-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'trash-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'trash-cli/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'trash-cli/cli.js' {
  declare module.exports: $Exports<'trash-cli/cli'>;
}
