// flow-typed signature: 9094b8768fb9d73de33d1844f402f0ae
// flow-typed version: <<STUB>>/@babel/plugin-proposal-unicode-property-regex_v7.4.0/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-unicode-property-regex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-unicode-property-regex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-unicode-property-regex/lib/index' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-unicode-property-regex/src/index' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/script-extensions/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/script-extensions/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/simple/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/simple/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/unicode-10/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/unicode-10/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/unicode-11/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/unicode-11/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/unicode-12/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/unicode-12/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/script-extensions/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/script-extensions/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/simple/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/simple/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/unicode-10/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/unicode-10/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/unicode-11/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/unicode-11/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/unicode-12/input' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/unicode-12/output' {
  declare module.exports: any;
}

declare module '@babel/plugin-proposal-unicode-property-regex/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-unicode-property-regex/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-unicode-property-regex/lib/index'>;
}
declare module '@babel/plugin-proposal-unicode-property-regex/src/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-unicode-property-regex/src/index'>;
}
declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/script-extensions/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/script-extensions/input'>;
}
declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/script-extensions/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/script-extensions/output'>;
}
declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/simple/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/simple/input'>;
}
declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/simple/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/simple/output'>;
}
declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/unicode-10/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/unicode-10/input'>;
}
declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/unicode-10/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/unicode-10/output'>;
}
declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/unicode-11/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/unicode-11/input'>;
}
declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/unicode-11/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/unicode-11/output'>;
}
declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/unicode-12/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/unicode-12/input'>;
}
declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/unicode-12/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-unicode-property-regex/test/fixtures/with-unicode-flag/unicode-12/output'>;
}
declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/script-extensions/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/script-extensions/input'>;
}
declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/script-extensions/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/script-extensions/output'>;
}
declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/simple/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/simple/input'>;
}
declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/simple/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/simple/output'>;
}
declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/unicode-10/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/unicode-10/input'>;
}
declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/unicode-10/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/unicode-10/output'>;
}
declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/unicode-11/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/unicode-11/input'>;
}
declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/unicode-11/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/unicode-11/output'>;
}
declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/unicode-12/input.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/unicode-12/input'>;
}
declare module '@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/unicode-12/output.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-unicode-property-regex/test/fixtures/without-unicode-flag/unicode-12/output'>;
}
declare module '@babel/plugin-proposal-unicode-property-regex/test/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-unicode-property-regex/test/index'>;
}
